### ISSUE TITLE
Mod causes HAN-D's drones to not work on allies

### ISSUE THREAD

**Issue by LordVGames** [Goorakh/NoAllyAttackBlock#1]
Not a bug, but it removes HAN-D's ability to heal others with his drones, so I feel like it's notable. The drones seem to rely on collision with an ally/enemy to do their thing. It would be good if an exception could be made for HAN-D's drones.

**Comment by Goorakh** [comment]
Thanks for the report, not going to promise anything since it seems like a pretty minor issue. And if it's a big deal you can always just disable this mod instead. I'll probably look into it if I end up updating the mod sometime.

**Comment by Goorakh** [comment]
This should now be possible to fix via the config in version 1.1.0.

Please re-open if this is not the case
